### ISSUE TITLE
Association to Fibaro Dimmer 2

### ISSUE THREAD

**Issue by cbho** [TedTolboom/dk.logichome#4]
Seems like the present app for ZHC5010 cannot handle units that are included in secure mode - and Homey includes as secure if possible (not possible to choose "non-secure" during pairing devices with Homey).
Can't find this documented in English, but the Danish guide for setting up the switch with Fibaro Home Center states explicitly the necessity of including dimmers in non-secure mode (http://logichome.dk/plugins/content/cwattachments/cwattachments/helpers/download.php?id=a87ff679a2f3e71d9181a67b7542122c&sid=39b988ec87d2556d0a877b6f0e782b2c).
Can this be fixed in some way?

**Comment by lurendrejer** [comment]
To save Ted some time repeating himself. :)

It isn't possible with homey apps/drivers.

Vi må hejse Kim op i en flagstang indtil han finder det :D

**Comment by lurendrejer** [comment]
Finder = fikser.
