### ISSUE TITLE
ZHC5002

### ISSUE THREAD

**Issue by SjaakKoning** [TedTolboom/dk.logichome#6]
Can you please add de ZHC5002, Wall switch to the app? 
http://logichome.dk/index.php/products/7-zhc5002-z-wave-coupler-for-gira

Very nice switch also. Thanks

**Comment by MrReaL** [comment]
Yeah, would really love this. Same device only two extra butons :)

**Comment by TedTolboom** [comment]
Initial driver is available in development branch...  
I appreciate your support in debugging.

Will close this issue for now
